use_frameworks!
install! 'cocoapods', :disable_input_output_paths => true
platform :ios, '11.0'

target 'EchoStorage_Example' do
#  pod 'EchoStorage', :path => '../'
  

  target 'EchoStorage_Tests' do
    inherit! :search_paths

  end
end
